#
# Configuration file for the Tabler bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/TablerBundle/blob/master/docs/configurations.md
#
tabler:
    options:
        # if "true" uses javascript to detect the OS mode and uses that, if "false" uses the "dark_mode" setting
        theme_auto: false
        # true = dark mode (light colors on dark background), false = normal mode (dark colors on light background)
        dark_mode: false
        # condensed = one nav-bar, false = two nav-bars
        navbar_condensed: true
        # true = dark mode, false = light mode (on header)
        header_dark: false
        # true = dark mode, false = light mode (on menu)
        navbar_dark: false
        # overlap = https://preview.tabler.io/layout-navbar-overlap.html
        navbar_overlap: false
        # true = boxed layout, false = full-screen
        boxed_layout: false
        # false = left to right, true = right to left
        rtl_mode: false
        # true = only avatar, false = show username and title as well
        user_menu_condensed: true
        # url to your company logo (if not with a protocol, the asset() helper will be used to create the url
        logo_url: ~
        # slate, gray, zinc, neutral, stone
        theme_base: "slate"
        # possible values: 0, 0.5, 1, 1.5, 2 | radius in pixels * 4
        theme_radius: "0.5"
        # blue, azure, indigo, purple, pink, red, orange, yellow, lime, green, teal, cyan
        theme_primary: "blue"

    knp_menu:
        enable: false
        main_menu: tabler_main
        breadcrumb_menu: false

    routes:
        tabler_welcome: home
        tabler_login: login
        tabler_login_check: login_check
        tabler_registration: registration
        tabler_registration_register: registration_register
        tabler_password_reset: resetting_request
        tabler_password_reset_sent: resetting_send_email

    icons:
        # used for the action_collapsebutton components
        collapse: fas fa-chevron-down
        # used for the password-reset template
        mail: far fa-envelope
        # used for the 404/500/... error page
        back: fas fa-long-arrow-alt-left
        # the following are only ideas to be used in your own templates
        about: fas fa-info-circle
        admin: fas fa-wrench
        bookmark: far fa-star
        calendar: far fa-calendar-alt
        clock: far fa-clock
        comment: far fa-comment
        copy: far fa-copy
        create: far fa-plus-square
        dashboard: fas fa-tachometer-alt
        delete: far fa-trash-alt
        download: fas fa-download
        edit: far fa-edit
        email: fa fa-at
        export: fas fa-file-export
        filter: fas fa-filter
        help: far fa-question-circle
        home: fas fa-home
        password: fas fa-key
        phone: fas fa-phone
        print: fas fa-print
        search: fas fa-search
        settings: fas fa-cog
        start: fas fa-play
        stop: fas fa-stop
        upload: fas fa-upload
        user: fas fa-user
