#
# Configuration file for the Tabler bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/TablerBundle/blob/master/docs/configurations.md
#
tabler:
    options:
        # true = dark mode (light colors on dark background), false = normal mode (dark colors on light background)
        dark_mode: true
        # for cache busting, can be dynamically changed woth the ContextHelper
        asset_version: "beta19"
        # condensed = one nav-bar, false = two nav-bars
        navbar_condensed: true
        # true = dark mode, false = light mode (on header)
        header_dark: false
        # true = dark mode, false = light mode (on menu)
        navbar_dark: false
        # overlap = https://preview.tabler.io/layout-navbar-overlap.html
        navbar_overlap: false
        # true = boxed layout, false = full-screen
        boxed_layout: false
        # false = left to right, true = right to left
        rtl_mode: false
        # true = only avatar, false = show username and title as well
        user_menu_condensed: true
        # url to your company logo (if not with a protocol, the asset() helper will be used to create the url
        logo_url: ~

    knp_menu:
        enable: false
        main_menu: tabler_main
        breadcrumb_menu: false

    routes:
        tabler_welcome: home
        tabler_login: login
        tabler_logout: logout
        tabler_login_check: login_check
        tabler_registration: registration
        tabler_registration_register: registration_register
        tabler_password_reset: resetting_request
        tabler_password_reset_sent: resetting_send_email

    icons:
        collapse: "fa6-solid:chevron-down"
        mail: "fa6-regular:envelope"
        back: "fa6-solid:left-long"
        about: "fa6-solid:circle-info"
        admin: "fa6-solid:wrench"
        bookmark: "fa6-regular:star"
        calendar: "fa6-regular:calendar-days"
        clock: "fa6-regular:clock"
        comment: "fa6-regular:comment"
        copy: "fa6-regular:copy"
        create: "fa6-regular:square-plus"
        dashboard: "fa6-solid:gauge"
        delete: "fa6-regular:trash-can"
        download: "fa6-solid:download"
        edit: "fa6-regular:pen-to-square"
        export: "fa6-solid:file-export"
        filter: "fa6-solid:filter"
        help: "fa6-regular:circle-question"
        home: "fa6-solid:house"
        password: "fa6-solid:key"
        phone: "fa6-solid:phone"
        print: "fa6-solid:print"
        search: "fa6-solid:magnifying-glass"
        settings: "fa6-solid:gear"
        start: "fa6-solid:play"
        stop: "fa6-solid:stop"
        upload: "fa6-solid:upload"
        user: "fa6-solid:user"
